export const ORDER_LISTS_REQUEST = "ORDER_LISTS_REQUEST";
export const ORDER_LISTS_SUCCESS = "ORDER_LISTS_SUCCESS";
export const ORDER_LISTS_FAILURE = "ORDER_LISTS_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILURE = "ORDER_DETAILS_FAILURE";

export const ORDER_PAYMENT_REQUEST = "ORDER_PAYMENT_REQUEST";
export const ORDER_PAYMENT_SUCCESS = "ORDER_PAYMENT_SUCCESS";
export const ORDER_PAYMENT_FAILURE = "ORDER_PAYMENT_FAILURE";
export const ORDER_PAYMENT_RESET = "ORDER_PAYMENT_RESET";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAILURE = "ORDER_DELIVERED_FAILURE";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

export const USER_ORDER_LIST_REQUEST = "USER_ORDER_LIST_REQUEST";
export const USER_ORDER_LIST_SUCCESS = "USER_ORDER_LIST_SUCCESS";
export const USER_ORDER_LIST_FAILURE = "USER_ORDER_LIST_FAILURE";
export const USER_ORDER_LIST_RESET = "USER_ORDER_LIST_RESET";
