# Generated by Django 6.0.7 on 2026-07-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_order_shippingprice_alter_order_taxprice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="countInStocks",
            new_name="countInStock",
        ),
    ]
