# Generated by Django 6.0.7 on 2026-08-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_countinstocks_product_countinstock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="taxPrice",
        ),
    ]
