# Generated by Django 6.0.7 on 2026-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_order_taxprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
