# Generated by Django 6.0.7 on 2026-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/placeholder.png",
                max_length=255,
                null=True,
                upload_to="",
            ),
        ),
    ]
